refactor: change parameter position into degrees
ichiro-its/robocup_client pull request #11
Opened 2021-06-04 04:15 UTC by Nathan24zz

2021-06-04 04:38 UTC, segara2410 reviewed
I think it is better to add another function `add_motor_position_in_degree` and change the current function into `add_motor_position_in_radian`.

2021-06-04 08:41 UTC, threeal requested changes
See individual comment for the requested changes.

2021-06-04 08:41 UTC, threeal commented on CMakeLists.txt
> +  musen Protobuf keisan)
Use alphabetical order (`kisan musen Protobuf`). do this to line 59 too.

2021-06-04 08:41 UTC, threeal commented on examples/client.cpp
> +  message.add_motor_position_in_degree("neck_yaw", 90.0);  // in degrees
Useless `// in degrees` comment, `add_motor_position_in_degree` already said that it's in degree.

2021-06-04 08:41 UTC, threeal commented on package.xml
> +  <exec_depend>keisan</exec_depend>
Wrong dependency specification. `depend` is equal to both `exec_depend` and `build_depend`. `exec_depend` only required during the execution time while `build_depend` only required during the build time. It actually doesn't matter during the `build-and-test` workflow (which explain why it passes that test), but will be a problem when deployed as a Debian package. See [this](http://wiki.ros.org/catkin/package.xml) for more information about dependency specification in the `package.xml`.

2021-06-04 08:41 UTC, threeal commented on src/robocup_client/message_handler.cpp
>  #include <string>
separate external library's headers with C/C++/system headers and use `keisan/keisan.hpp` instead of `keisan/angle.hpp`.

2021-06-05 16:33 UTC, threeal approved these changes
LGTM

2021-06-05 16:36 UTC, maroqijalil approved these changes
lgtM

2021-06-05 16:36 UTC, merged